# This is a basic workflow to help you get started with Actions


name: email_nofication

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Read HTML file
        id: read_html
        run: |
          # Replace 'path/to/your/file.html' with the actual path to your HTML file
          html_file="test.html"
          html_content=$(cat "$html_file")
          echo "{html_content}={html_content}" >> $GITHUB_OUTPUT
      
      

      # Here is the notification step
      - name: CINotify Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          to: avidyasagar@suncor.com
          subject: 'Workflow completed successfully'
          # Use the HTML content from the previous step as the email body
          html_body: "test.html"
          # body: ${{ steps.read_html.outputs.html_content }}
      
          
