# This is a basic workflow to help you get started with Actions


name: email_nofication

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


      - name: Attach HTML File
        uses: actions/upload-artifact@v2
        with:
          name: my-html-file # Replace with a unique name for your artifact
          path: TestRepo/test.html # Replace with the actual path to your HTML file


      # Here is the notification step
      - name: CINotify Email
        uses: cinotify/github-action@v1.1.2
        with:
          to: avidyasagar@suncor.com
          subject: 'Workflow completed successfully'
          body: TestRepo/test.html

